version: "3.8"
services:
  app:
    image: socket-server-img
    container_name: simple-socket-server
    build: .
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
    name: main
    external: true
